export enum Exception {
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_CREDENTIAL_INVALID = 'USER_CREDENTIAL_INVALID',
  USER_IS_LOCK = 'USER_IS_LOCK',
  USER_ROLE_ACCESS_DENIED = 'USER_ROLE_ACCESS_DENIED',
  USER_EMAIL_FORMAT = 'USER_EMAIL_FORMAT',
  USER_PASSWORD_IS_EMPTY = 'USER_PASSWORD_IS_EMPTY',
  USER_PASSWORD_CONTAINS_SPACES = 'USER_PASSWORD_CONTAINS_SPACES',
  USER_INVALID_AUTH_TYPE = 'USER_INVALID_AUTH_TYPE',

  CREATION_TITLE_AND_CATEGORY_EXISTS = 'CREATION_TITLE_AND_CATEGORY_EXISTS',

  REVIEW_GRADE_INVALID_FORMAT = 'REVIEW_GRADE_INVALID_FORMAT',

  IMAGE_UPLOAD = 'IMAGE_UPLOAD',
  IMAGES_DELETE = 'IMAGES_DELETE',

  JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_ACCESS_TOKEN_INVALID = 'JWT_ACCESS_TOKEN_INVALID',
  JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_INVALID = 'JWT_REFRESH_TOKEN_INVALID',
}
