export enum Exception {
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_CREDENTIAL_INVALID = 'USER_CREDENTIAL_INVALID',
  USER_IS_LOCK = 'USER_IS_LOCK',
  USER_ROLE_ACCESS_DENIED = 'USER_ROLE_ACCESS_DENIED',

  JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_ACCESS_TOKEN_INVALID = 'JWT_ACCESS_TOKEN_INVALID',
  JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_INVALID = 'JWT_REFRESH_TOKEN_INVALID',
}
